### ISSUE TITLE
Allow multiple ElasticLoadBalancers to be defined

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando-stups/senza#109]
We have a use case where we require multiple ELB's to be available for one Auto Scaling Group.

Currently, ElasticLoadBalancer is translated to a list of LoadBalancerNames with length 1.

**Comment by hjacobs** [comment]
Can you describe your use case? One ELB can use multiple listeners (ports) etc -- I just wonder were more than one makes sense...

**Comment by feikesteenbergen** [comment]
1 LoadBalancer which checks for PostgreSQL master instances and redirects to the master
1 LoadBalancer which checks for PostgreSQL slave instances and redirects to (a) slave

**Comment by hjacobs** [comment]
OK, I see :+1:

**Comment by tuxlife** [comment]
A Solution is very easy:

```
  - AppLoadBalancer:
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      HealthCheckPath: /master
      SecurityGroups:
        - app-hello-world-lb
      Scheme: internet-facing
      VersionDomain: foobar-{{Arguments.version}}.example.org
      MainDomain: master.example.org
  - SlaveLoadBalancer:
      LoadBalancerName: "app-hello-world-slave-{{Arguments.ApplicationId}}"
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      HealthCheckPath: /slave
      SecurityGroups:
        - app-hello-world-lb
      Scheme: internet-facing
      VersionDomain: foobar-{{Arguments.version}}-slave.example.org
      MainDomain: slave.example.org
```

@feikesteenbergen can you please test this?

**Comment by hjacobs** [comment]
@tuxlife you still need to connect the ELB to the ASG --- this is what's missing (TaupageAutoScalingGroup only allows one ELB currently)

**Comment by tuxlife** [comment]
@hjacobs I think, this works with 1f6e7d2

```
  - AppServer:
      Type: Senza::TaupageAutoScalingGroup
      InstanceType: t2.micro
      SecurityGroups:
        - app-hello-world
      IamRoles:
        - app-hello-world
      ElasticLoadBalancer:
        - AppLoadBalancer
        - SlaveLoadBalancer
      AssociatePublicIpAddress: false # change for standalone deployment in default VPC
      TaupageConfig:
        application_version: "{{Arguments.ImageVersion}}"
        runtime: Docker
        source: "stups/hello-world:{{Arguments.ImageVersion}}"
        health_check_path: /
        ports:
          8080: 8080
  - AppLoadBalancer:
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      HealthCheckPath: /master
      SecurityGroups:
        - app-hello-world-lb
      Scheme: internet-facing
      VersionDomain: foobar-{{Arguments.version}}.example.org
      MainDomain: master.example.org
  - SlaveLoadBalancer:
      LoadBalancerName: "app-hello-world-slave-{{Arguments.ApplicationId}}"
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      HealthCheckPath: /slave
      SecurityGroups:
        - app-hello-world-lb
      Scheme: internet-facing
      VersionDomain: foobar-{{Arguments.version}}-slave.example.org
      MainDomain: slave.example.org
```
