### ISSUE TITLE
Add an option (flag) to specify which domain should be used with senza create

### ISSUE THREAD

**Issue by angeldimitrov** [zalando-stups/senza#121]
In case there are more than one domain associated with an account, senza shows the following dialog:
```bash
senza create senza.yml v1 v1
Generating Cloud Formation template..Please select the domain
1) domain one
2) domain two
```
This change was introduced with https://github.com/zalando-stups/senza/commit/a299d2df565700ed864789928d59ad8bc7ce9755

Since we use senza thru our CD it will be good to have a flag to specify which domain should be used to prevent the dialog.

**Comment by hjacobs** [comment]
@angeldimitrov you can select the domain already with Senza by setting MainDomain / VersionDomain in your Senza definition YAML, see http://docs.stups.io/en/latest/components/senza.html#senza-weighteddnselasticloadbalancer

Example from our Open Source registry:
```yaml
# creates an ELB entry and Route53 domains to this ELB
  - AppLoadBalancer:
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      HealthCheckPath: /.well-known/health
      SSLCertificateId: opensource-zalan-do-comodo
      SecurityGroups: [app-os-registry-lb]
      Scheme: internet-facing
      MainDomain: registry.opensource.zalan.do
      VersionDomain: registry-{{SenzaInfo.StackVersion}}.opensource.zalan.do

**Comment by hjacobs** [comment]
Closing this issue as the proposed solution should work.

**Comment by kenden** [comment]
Just a note if you get this issue without using Senza's own `AppLoadBalancer` but just "pure yaml Cloudformation":
then `"{{AccountInfo.Domain}}"` cannot be used. 
Just hardcode the domain in the template or use a template pamameter.
Ex:
```
  Route53:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneName: mycompany.net # cannot use "{{AccountInfo.Domain}}" here
      Comment: "Nope"
      RecordSets:
        -
          Name:
            Fn::Join:
              - ""
              -
                - "{{Arguments.Route53Name}}"
                - "."
                - "mycompany.net" # cannot use "{{AccountInfo.Domain}}" here
          Type: "A"
          AliasTarget:
            DNSName:
              Fn::Join:
                - ""
                -
                  - "dualstack."  # to support both IPV6 and IPV4
                  - Fn::GetAtt: [ELB, DNSName]

            EvaluateTargetHealth: false
            HostedZoneId:
              Fn::GetAtt: [ELB, CanonicalHostedZoneNameID]
```
