### ISSUE TITLE
KeyError when deploying basic Senza stack

### ISSUE THREAD

**Issue by mfellner** [zalando-stups/senza#126]
We use a very basic Senza definition to create just 1 database, like so:

```yaml
SenzaInfo:
  StackName: db-foobar
Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: db-foobar
      DBName: postgres
      Engine: postgres
      EngineVersion: 9.4.1
      MasterUsername: postgres
      MasterUserPassword: postgres
      DBInstanceClass: db.t2.small
      # ... truncated for brevity
```

This causes the following error:

```
File "/usr/local/lib/python3.5/site-packages/senza/cli.py", line 554, in create_cf_template
    stack_name = "{0}-{1}".format(data['Mappings']['Senza']['Info']['StackName'],
KeyError: 'Mappings'
```

Adding this line to `cli.py#evaluate` fixes the problem (just a hack, of course):

```python
definition["Mappings"] = {"Senza": {"Info": info} }
```

Maybe related to #98?
