### ISSUE TITLE
Region aware YAML files

### ISSUE THREAD

**Issue by vetinari** [zalando-stups/senza#155]
Please make 
* the region as passed to senza via the --region option available as replacement option in the yaml file. There is no need for duplication options like `senza create --region some-where-1 myapp.yaml stackVersion $version some-where-1`
* mappings which can be defined ourselves which can then be inserted in place, like 

```    MyApp:
        - some-where-1:
             DockerEnv:
                 SOME_KEY: "aws:kms:$for_some_where_1"
        - some-where-2:
             DockerEnv:
                 SOME_KEY: "aws:kms:$for_some_where_2"
```

and something like

```      TaupageConfig:
           environment: 
               {MyApp: {{REGION}: DockerEnv}
```

**Comment by hjacobs** [comment]
Can you describe your use case? Adding the region to the template variables makes sense, but I want to understand how you use it. Your application can always retrieve the current region from the EC2 metadata service, i.e. having another level below "environment" makes IMHO no sense..

**Comment by vetinari** [comment]
We need per region KMS encrypted secrets. Having them all in one file would make it easier to handle installations in different regions with setups which is the same everywhere except for the secrets.

**Comment by lmineiro** [comment]
We solved this with some Makefile includes.

Makefile
```
REGION ?= eu-central-1
ACCOUNT ?= pathfinder
include conf/$(ACCOUNT)/$(REGION).mk
```

conf/pathfinder/eu-central-1.mk
```
SCALYR_KEY="aws:kms:encrypted-value-with-eu-central-kms-key-for-scalyr-key"
SOME_SECRET="aws:kms:encrypted-value-with-eu-central-kms-key"
CERTIFICATE_ARN="arn:aws:iam::xxxxxx:server-certificate/foo"
MINT_BUCKET="pathfinder-account-mint-bucket"
```

Then we define senza template arguments for those that the Makefile's `deploy` target sets from the incuded acount/region specific file

**Comment by whiskeysierra** [comment]
Isn't it possible to reference the current region with plain old cloudformation already?
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

    {"Ref" : "AWS::Region"}

Or am I missing the point here?

**Comment by kenden** [comment]
It is possible to use `Ref: AWS::Region` to find the region is the template. 
ex:
```
Fn::FindInMap: [LoadBalancerSubnets, {"Ref": "AWS::Region"}, Subnets]
```

However, it can be less practical  to use this in the user data.
It would be nice to be able to access the param passed to `--region` when calling Senza. 
Maybe with `{{SenzaInfo.Region}}` ?

Example for why it might be more difficult to access `Ref: AWS::Region` in the userdata:
```
  LaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      InstanceType: m4.xlarge
      ImageId: ami-28fb711e
      IamInstanceProfile: configLoader
      InstanceMonitoring: true
      AssociatePublicIpAddress: false
      SecurityGroups:
        - Ref: MySecGroup
      UserData:
        Fn::Base64:
          | # '|' Joins multiple lines into one string but keep line breaks
            #!/usr/bin/env bash

            set -ve # verbose and exit if any errors

            echo "Ref: AWS::Region"  # <------ this will just echo "Ref: AWS::Region"
            # It would be nice to be able to access the param passed to --region when calling Senza.
            # Maybe like this?
            # echo "{{SenzaInfo.Region}}"
            # ... do more things
```

As a workaround, you can use this in the userdata:
```
REGION=$(ec2metadata --availability-zone | sed 's/.$//')```
# ---> $REGION is now eu-west-1, us-east-1. eu-central-1....
```
