### ISSUE TITLE
environment-{{Arguments.EnvType==sandbox}}

### ISSUE THREAD

**Issue by elgalu** [zalando-stups/senza#187]
Disclaimer note: this could also be solved through #100 

Would you be willing to accept a PR to add:

```yaml
TaupageConfig:
  environment-{{Arguments.EnvType==sandbox}}:
    DATABASE_HOST: "sql.sandbox.com"
  environment-{{Arguments.EnvType==live}}:
    DATABASE_HOST: "sql.production.com"
```

Or perhaps even shorter:

```yaml
TaupageConfig:
  environment-sandbox:
    DATABASE_HOST: "sql.sandbox.com"
  environment-live:
    DATABASE_HOST: "sql.production.com"
```

i.e. to avoid:

- context switching (managing more than 1 senza yaml file for the same app)
- command line arguments overload when dealing with senza.yaml variations, 
i.e. having to pass a very long list of arguments to senza create in the end resulting into `Template format error: 'Description' length is greater than 1024` particularly when using aws:kms
- having to add EnvType dependant varations logic outside of the senza.yaml file in the app itself or the docker entry point.

Additional note: I wouldn't limit this to `TaupageConfig:` => `environment` but to any senza key value.
