### ISSUE TITLE
Parameter constraints

### ISSUE THREAD

**Issue by outime** [zalando-stups/senza#204]
CloudFormation templates receiving _Parameters_ have the possibility to apply certain constraints as shown [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) (scroll down to "Properties", seems it can't be directly linked). I found myself in situations where this could be useful in some Senza templates I've written, such as:

* Validating an URL which is an endpoint used by the app
* Restricting the length of a variable since app limits it
* Providing a list of valid values to specify the [volume types](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html)

So let's say we have this:

```
SenzaInfo:
  StackName: test-stack
  Parameters:
    - VolumeType:
        Description: "Type of EBS volume to be used."
        Default: "gp2"
```

What I propose is that we could have something like:

```
SenzaInfo:
  StackName: test-stack
  Parameters:
    - VolumeType:
        Description: "Type of EBS volume to be used."
        Default: "gp2"
        AllowedValues: ["gp2", "io1", "st1", "sc1", "standard"]
```

Which would have a similar structure to CloudFormation.

I'm willing to write the features by myself if no one else wants to do it. What I'd do is to implement the constraints in `parse_args()` but I'm open to suggestions.
