### ISSUE TITLE
Error "No Taupage AMI found" when running Senza in region eu-central-1

### ISSUE THREAD

**Issue by kenden** [zalando-stups/senza#230]
I am running Senza to create a stack in the region eu-west-1, it is working fine.
I am not using Taupage (we already have our own system to manage the AMIs).
Instead, I create my own Autoscalling group, Launch Configuration and ELB in the Senza template. This looks like this:
```
LaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
        ImageId: "{{Arguments.AMIImage}}"
        ....
  ASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
    ...
ELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
        ....
```

When running this in the region eu-central-1, this fails:
```
senza create --region eu-central-1 my-template.yml stack1 Environment="production" DockerImgVer="v747" AMIImage="ami-28fb711b"  #passing the ami as param.
Generating Cloud Formation template.. EXCEPTION OCCURRED: No Taupage AMI found
```

This seems to be throw from [here](https://github.com/zalando-stups/senza/blob/2348a1dc0a860d8ce3f134cd5d1289a956a47860/senza/components/stups_auto_configuration.py#L23):

**Comment by hjacobs** [comment]
@kenden probably your account (or region) was freshly set up and we need to share the Taupage AMI with you.

**Comment by kenden** [comment]
Thanks @hjacobs.
I don't use Taupage (yet?), that's why it's not in the region, I suppose.

I found a better workaround though.

I removed
```
SenzaComponents:
  - Configuration:
      Type: Senza::StupsAutoConfiguration
```
from the Senza template. Without this `find_taupage_image()` is not called at all and doesn't fail.

I was only using `SenzaComponents` to get Subnets with:
```
Fn::FindInMap: [LoadBalancerSubnets, {"Ref": "AWS::Region"}, Subnets]
```
I replaced that by adding a mapping and referring to it.
```
Mappings:
  production:
    Subnets:
      value:
        - subnet-b91e59b1
        - subnet-e338181e
  test:
    Subnets:
      value:
        - subnet-e315ec95
        - subnet-849d6cdc

Fn::FindInMap: ["{{Arguments.Environment}}", Subnets, value]
```

It would be nice to be able to get this mapping LoadBalancerSubnets automatically but I understand if Taupage is required if one decides to use `SenzaComponents`. (Extra documentation could be good here).
