### ISSUE TITLE
SSLCertificateId set to null even when included in the .yaml file

### ISSUE THREAD

**Issue by smourapina** [zalando-stups/senza#334]
While trying to deploy with senza `Senza 2.0.121`, the following error appears:

`EXCEPTION OCCURRED: An error occurred (ValidationError) when calling the CreateStack operation: 'null' values are not allowed in templates
Validation Error: 'null' values are not allowed in templates`

Using senza print, the field `SSLCertificateId` is set to `null`, even though the `.yaml` file includes this:

`"Listeners": [
                    {
                        "InstancePort": 8080,
                        "LoadBalancerPort": 443,
                        "PolicyNames": [],
                        "Protocol": "HTTPS",
                        "SSLCertificateId": null
                    }
                ]`

**Comment by Jan-M** [comment]
https://github.com/zalando-stups/senza/blob/master/senza/components/elastic_load_balancer.py#L27

If my eyes don't trick me the get ssl cert does not return anything?

**Comment by alterrebe** [comment]
Got the same problem after updating to 2.0.121. Original YAML:
```
Parameters:
   - SSLCert:
         Description: "SSL certificate ID"
         Default: wildcard-discovery-fleek-style-comodo-20160301
   ...
SenzaComponents:
   - Configuration:
      Type: Senza::StupsAutoConfiguration
   - AppLoadBalancer:
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8080
      Scheme: internet-facing
      SSLCertificateId: "{{Arguments.SSLCert}}"
```
The result CF template:

    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Elasticdiscovery (AppId: elasticdiscovery-ci,  SSLCert: wildcard-discovery-fleek-style-comodo-20160301, ...)",
    ...
                "Listeners": [
                    {
                        "InstancePort": 8080,
                        "LoadBalancerPort": 443,
                        "PolicyNames": [],
                        "Protocol": "HTTPS",
                        "SSLCertificateId": null
                    }
                ],
