### ISSUE TITLE
Is it possible to use multi-values cloudformation parameters, e.g. List<AWS::EC2::Subnet::Id> with Senza?

### ISSUE THREAD

**Issue by kenden** [zalando-stups/senza#348]
I would like to pass List parameters to my Template.
Ex, below: `SubnetIDs` would be a list of Subnets.

```
SenzaInfo:
  StackName: test

  Parameters:
    - SubnetIDs:
        Type: List<AWS::EC2::Subnet::Id>
        Description: IDs of subnets where to add/update the ELB.
```

However, how can I provide this parameter to the template?
I tried `--parameter-file senza-param.yml` with the content:

```
SubnetIDs: subnet-fa6dab92, subnet-a273ecd6
```

but it becomes just one string instead of a list.

Would this way work?

```
senza create senza-template.yml ver1 SubnetIDs="subnet-fa6dab92, subnet-a273ecd6"  # No, String type, not list
senza create senza-template.yml ver1 SubnetIDs=[subnet-fa6dab92, subnet-a273ecd6] # invalid?
senza create senza-template.yml ver1 SubnetIDs=[ "subnet-fa6dab92", "subnet-a273ecd6"]  # invalid?
```

My workwaround is to use 2 parameters, SubnetID1 and SubnetID2, but we have test and prod environments with different numbers of parameters so it's not very practical.

Vesion: Senza 2.0.121
