### ISSUE TITLE
Allow to include content from external file in template

### ISSUE THREAD

**Issue by kenden** [zalando-stups/senza#404]
Feature Request: Allow to include content from external file

The UserData parts of a template can get pretty big.
It would be nice to be able to include those parts from separate files.
Having them in separate files would also allow to syntax-check them in code editors.

Example: Instead of having part of a senza template file look like:
```
...
Resources:
  InstanceController
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-west-1a
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: '30'
            VolumeType: gp2
      IamInstanceProfile:
        Ref: IAMInstanceProfileController
      ImageId: ami-a94c02da
      InstanceType: m3.medium
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeleteOnTermination: true
      Tags:
        - Key: KubernetesCluster
          Value: kubernetes-kube-aws
        - Key: Name
          Value: kubernetes-kube-aws-kube-aws-controller
      UserData:
        Fn::Base64:
          |
            #cloud-config <---- this part can be long/complex. It would be better in a separate file
            coreos:
              update:
                reboot-strategy: "off"
              flannel:
                interface: $private_ipv4
                etcd_endpoints: http://10.0.40.50:2379
              etcd2:
                name: controller
                advertise-client-urls: http://$private_ipv4:2379
                initial-advertise-peer-urls: http://$private_ipv4:2380
                listen-client-urls: http://0.0.0.0:2379
                listen-peer-urls: http://0.0.0.0:2380
                initial-cluster: controller=http://$private_ipv4:2380
              units:
                - name: etcd2.service
            # ...
            # (loooong cloud-config)  
            # ...
```

We could replace the userdata content by something like ` {{ SenzaReplace: ./cloudinit.yaml }}`
It could look like this:
```
...
Resources:
  InstanceController
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-west-1a
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: '30'
            VolumeType: gp2
      IamInstanceProfile:
        Ref: IAMInstanceProfileController
      ImageId: ami-a94c02da
      InstanceType: m3.medium
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeleteOnTermination: true
      Tags:
        - Key: KubernetesCluster
          Value: kubernetes-kube-aws
        - Key: Name
          Value: kubernetes-kube-aws-kube-aws-controller
      UserData:
        Fn::Base64:
          |
            {{ SenzaReplace: ./cloudinit.yaml }}
```
and file `cloudinit.yaml` would then have the content:
```
#cloud-config
coreos:
  update:
    reboot-strategy: "off"
  flannel:
    interface: $private_ipv4
    etcd_endpoints: http://10.0.40.50:2379
  etcd2:
    name: controller
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://0.0.0.0:2380
    initial-cluster: controller=http://$private_ipv4:2380
  units:
    - name: etcd2.service
# ...
# (loooong cloud-config)  
# ...
```
That content could be yaml/bash/sh... and could syntax-checked (in a code editor or a validation tool during continuous integration).
Senza would then replace {{ SenzaReplace: ./cloudinit.yaml }} by the content of cloudinit.yaml.

### Alternative 
Another way could be to replace:
```
UserData:
  Fn::Base64:
    |
      {{ SenzaReplace: ./cloudinit.yaml }}
```
By simply:
```
UserData: {{ SenzaUserData: ./cloudinit.yaml }}
```
Senza would then replace {{ SenzaUserData: ./cloudinit.yaml }} by the equivalent of:
`cat cloudinit.yaml | base64 | gunzip` to save space (the maximum size of a Cloudformation template is 51,200 bytes and UserData can occupy a lot of space).
