### ISSUE TITLE
Senza disregard "NoEcho" attribute for parameters when creating default stack description

### ISSUE THREAD

**Issue by alterrebe** [zalando-stups/senza#425]
Senza creates a default description (`components/configuration.py`, method `get_default_description()` ) by concatenating the stack name with all the parameters values used to create the stack. The values are shown in clear text even if a particular parameter is defined as _NoEcho_, so the behavior defeats the purpose of the _NoEcho_ attribute.

Senza should honor the _NoEcho_ attribute and replace such parameters' values with `****` in the same way as AWS console does.

**Comment by alterrebe** [comment]
A temporary workaround is to provide an explicit stack description by duplicating the description clause both inside `SenzaInfo` and on the top level:
```
SenzaInfo:
   StackName: foo
   Description: some description
   ...

Description: same description

SenzaComponents:
   ...
```

It prevents Senza from generating the default description. A drawback is that we don't see other  parameters values in the stacks list.
