### ISSUE TITLE
ELB v2 custom properties

### ISSUE THREAD

**Issue by mirzali** [zalando-stups/senza#439]
I would need to set a custom property for the new App LB:

```yaml
  Properties:
    LoadBalancerAttributes:
    - Key: idle_timeout.timeout_seconds
      Value: '300'
```
at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#d0e74853

However, currently this doesn't seem to be possible. So I wonder if this feature is planned and how soon?
