### ISSUE TITLE
Exporting ApplicationName as an AWS tag for ELBs

### ISSUE THREAD

**Issue by jkozlowicz** [zalando-stups/senza#451]
We need a way to identify ELBs of multiple instances of the same application (i.e. multiple instances of `LizzyAgent` hosted in different AWS accounts).

I added a way to do this by setting `ApplicationName` attribute in `SenzaInfo` section:
```
# basic information for generating and executing this definition
SenzaInfo:
  StackName: hello-<team_name>
  ApplicationName: hello-app
```
which will be exported as an AWS tag for the ELB.
