### ISSUE TITLE
Allow CloudFormation Ref function in TaupageConfig

### ISSUE THREAD

**Issue by marco-hoyer** [zalando-stups/senza#46]
I would like to create cloudformation resources like SQS queues or RDS databases in my app.yml and handover resource properties directly into the instances configuration. As environment variables f.e. This would need senza to parse the TaupageConfig section and look for "Ref: foo" statements to process prior to base64 encoding.

**Comment by hjacobs** [comment]
:+1:

**Comment by Jan-M** [comment]
DB_HOST: {"Fn::GetAtt" : [DBInstance, Endpoint.Address]}
DB_PORT: {"Fn::GetAtt" : [DBInstance, Endpoint.Port]}

Similar issue with the above config, probably time to implement this feature for "easy" service discovery.

**Comment by chris-zen** [comment]
My use case:
```yaml
Resources:
  ExhibitorBucket:
    Type: AWS::S3::Bucket
SenzaComponents:
  - ExhibitorService:
      Type: Senza::TaupageAutoScalingGroup
      TaupageConfig:
        environment:
          S3_BUCKET: [{Ref: "ExhibitorBucket"}]
          S3_PREFIX: "exhibitor"
```

Translates into:
```
"UserData": {
    "Fn::Base64": "#taupage-ami-config\nenvironment:\n  S3_BUCKET:\n  - Ref: ExhibitorBucket\n  S3_PREFIX: exhibitor\n..."
}
```

I see that it is a complex problem in the sense that the result of the ref is not known until the cloudformation template has been deployed, but the EC2 instance data has to be known in advance, so it is like the dog that bites his cue.

I would like to study the problem and see whether I can contribute a solution or not. Any advice on where to start by ?
