### ISSUE TITLE
senza update changes nothing if only tags changed

### ISSUE THREAD

**Issue by avaczi** [zalando-stups/senza#470]
Changing an existing tag to some other value results in a NO UPDATE upon `senza update`.

```
SenzaInfo:
  StackName: spilo
  Tags:
    - SpiloCluster: "{{Arguments.version}}"
    - Environment: "live" # changed from something else
```

```
senza update this.yaml this
Generating Cloud Formation template.. OK
Updating Cloud Formation stack spilo-loungemarketingblacklist.. NO UPDATE
```

Might be related to https://github.com/zalando-stups/senza/issues/413, but there the end is somehow missing.
