### ISSUE TITLE
Components names should update VPC DHCP to allow service discovery

### ISSUE THREAD

**Issue by elgalu** [zalando-stups/senza#53]
Assuming component names are unique in Senza it would be convenient to setup the VPC DHCP or some internal DNS within the VPC so N deployed background components designed to work together but without exposing them through a public DNS can communicate with an internal hostname that resolves to the AWS private ip of the instances:

```yaml
SenzaComponents:
  - ComponentName1:
      Type: ComponentType1
      SomeComponentProperty: "some value"
  - ComponentName2:
      Type: ComponentType2
```

e.g. `component-name-1.local` resolves to `172.31.144.180`
e.g. `component-name-2.local` resolves to `172.31.144.181`

Or instead of `local` could also be `eu-west-1.compute.internal` varying on the region for example. 

Should be [technically possible](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html)
> By default, all instances in a nondefault VPC receive an unresolvable host name that AWS assigns (for example, ip-10-0-0-202). You can assign your own domain name to your instances

Google Cloud apparently solves it out of the box: https://cloud.google.com/compute/docs/instances-and-network#communicating_with_instances

Perhaps this is the wrong approach and my use case can be solved via etcd? in which case how? I searched etcd in http://stups.readthedocs.org/ but couldn't find it.
