### ISSUE TITLE
Support for Elastigroups [SpotInst] ignores VPCZoneIdentifier

### ISSUE THREAD

**Issue by mo-gr** [zalando-stups/senza#543]
When the Appserver has a `VPCZoneIdentifier` configuration, like:
```yaml
VPCZoneIdentifier:
          Fn::FindInMap:
            - LoadBalancerSubnets
            - Ref: AWS::Region
            - Subnets
```

This should be translated to the Elastigroup create argument `compute.subnetIds`.

Currently, this does not happen, resulting in instances being potentially created in the wrong subnets.

A workaround is to explicitly specify the `compute.subnetIds` argument in the Elastigroup configuration:
```yaml
Elastigroup:
  compute:
    subnetIds:
      Fn::FindInMap:
            - LoadBalancerSubnets
            - Ref: AWS::Region
            - Subnets
```
