### ISSUE TITLE
Allow default values for Parameters

### ISSUE THREAD

**Issue by lmineiro** [zalando-stups/senza#70]
It would be nice to be able to specify a default value for Parameters. For ex.

```
Parameters:
  - ClusterSize:
    Description: "The size (number of nodes) for the new Cassandra cluster."
    DefaultValue: 5
````

This can be challenging, due to the order based parameter mapping. Eventually, Optional parameters would have to be at the end and not possible to skip them.

It would be a nice addition.
